### ISSUE TITLE
Proposal to allow files to pass through `dest` without writing them to disk. 

### ISSUE THREAD

**Issue by doowb** [gulpjs/vinyl-fs#193]
@jonschlinkert and I have been trying to figure out a way to pipe files through `dest` but not actually write the files to disk or create the directories.

The goal is to ensure the file properties are updated using the same logic from [prepare-write](https://github.com/gulpjs/vinyl-fs/blob/master/lib/prepare-write.js), then use the properties in another stream plugin. Our specific use case is to create a directory tree from the destination file paths.

We've come up with [this solution](https://github.com/doowb/vinyl-fs/tree/write-file), which uses a `file.writeFile` property to skip [creating the destination directory](https://github.com/doowb/vinyl-fs/blob/write-file/lib/prepare-write.js#L50-L53) and [return early in `write-contents`](https://github.com/doowb/vinyl-fs/blob/write-file/lib/dest/write-contents/index.js#L9-L12) when set to `false`.

Will you accept a pull request with this change, or suggest another way we could accomplish the same thing?

Thanks.

**Comment by jonschlinkert** [comment]
fwiw we searched around quite a bit for other solutions/ideas before coming to this solution. 

I can't think of another way of being able to emulate the file tree - exactly as it would be if it were processed by `gulp.dest()`, but without actually writing the files. Every other way we came up with had some kind of drawback.

**Comment by phated** [comment]
3 ideas come to mind.

* An option for dest called write to mirror read on src. 
* A separate method that just prepares the file. 
* (my favorite currently) Split the prepare logic into a module that exposes a stream and use that internally in vinyl-fs.

The reason I like the last one is that other vinyl adapters could use it to emulate our behavior.

**Comment by jonschlinkert** [comment]
> The reason I like the last one is that other vinyl adapters could use it to emulate our behavior.

I love that idea. It might resolve/allow other things we've wanted to do.

**Comment by doowb** [comment]
> Split the prepare logic into a module that exposes a stream and use that internally in vinyl-fs.

I think this is my favorite also. I was thinking `vinyl-prepare` or `vinyl-prewrite` for the name.

Also, I think that the `mkdirp` call should be moved to `write-contents`. I'll set the `dirMode` on the `file` so it can be used like this:

```js
var writeFolder = path.dirname(file.path);
fo.mkdirp(writeFolder, file.dirMode, onMkdirp);
```

If this sounds good, I'll put a repo and PR together.

**Comment by contra** [comment]
Why don't you write your own stream that uses the prepare function on the file and not use dest? Would only be 3 lines of code - I don't think this is common enough of a case to warrant adding an option to dest for it, but we can make sure that the prepare logic is accessible so you can use it in your own streams.

**Comment by jonschlinkert** [comment]
> Why don't you write your own stream that uses the prepare function

I think that's what @phated is suggesting. I agree, this would be the way to go. 

> I don't think this is common enough of a case to warrant adding an option to dest for it

I also agree with this. plus, adding an option to `dest` wouldn't be useful for this unless it was a function, and that seems heavy for this.

> I don't think this is common enough of a case

Lol yeah I suspect it's pretty rare considering it's not possible atm. jk

> we can make sure that the prepare logic is accessible so you can use it in your own streams.

That would be awesome. I'd love to avoid having to duplicate the code and keep parity.  

The last thing we want to do is add feature bloat, but I know we'll get a lot of use out of this. I think other devs will find it useful too, once it's exposed. With only a few lines of code it opens up the possibility to do other interesting things

**Comment by phated** [comment]
Interesting side note that I didn't want to type on my phone last night: in refactoring the tests, I've found a lot of inconsistencies with the `prepareWrite` module and would like to have it fully unit tested apart from `gulp.dest`.  So this issue comes at an opportune time.  We also want to reach parity with the `gulp.src` method so a module could expose a src/dest prepare stream.  As soon as I finish this test refactor, I'll look into splitting it apart.

**Comment by erikkemperman** [comment]
Kind of related:

I looked into the two skipped tests in `test/dest.js`. The error they expect should come from `prepareWrite` (https://github.com/gulpjs/vinyl-fs/blob/master/lib/prepare-write.js#L32) but currently we don't get that far: through2 never gets around to calling the `saveFile` function (https://github.com/gulpjs/vinyl-fs/blob/master/lib/dest/index.js#L20)  because nothing is ever piped in to `dest` by these tests.

But actually `prepareWrite` seems like the wrong place to handle options anyway, so maybe this is part of a bigger issue.

I like the proposal of the proposed refactor of `prepareWrite`, if I understand it correctly; change it to a wrapping stream, much like is done for `wrap-with-vinyl-file` in `src`, and then make that (those) available for external use.

Maybe make a point of cleaning up options processing as part of the same effort? I have some half-baked work in this direction, but got distracted by diving into the value-or-function helper. Let me know if there's anything you think I might contribute.

**Comment by phated** [comment]
Package scaffolded at https://github.com/gulpjs/vinyl-prepare

**Comment by doowb** [comment]
@phated I have some code I started on and can send a PR. I'll update the tests with what you just merged in and add specific `prepare` tests. I can also include `prepare.src` which I think will handle the `options` and `wrap-with-vinyl-file` functionality.

**Comment by phated** [comment]
@doowb awesome, I didn't see where you were working on stuff so I just pushed the logic split from vinyl-fs (no tests).  I tested it against vinyl-fs but needed to add pumpify (see https://github.com/gulpjs/vinyl-fs/tree/prepare-stream)

**Comment by doowb** [comment]
> I didn't see where you were working on stuff

np... i didn't push anything up, but basically made the same changes as you.

> but needed to add pumpify

I did something similar, but used `duplexify` to match what the sourcemaps part was doing.

When I was adding tests (for high watermark and slow streams), I needed to use `sink` around `prepare`. Do you think `sink` should be externalized so it can be used in `vinyl-prepare`?

**Comment by phated** [comment]
Due to this always being a Transform stream, the tests will have to always use `from` and `to` or `concat`.  The reason vinyl-fs sinks is due to a bad pattern we support (sometimes a Transform stream/sometimes a writeable)

**Comment by doowb** [comment]
That makes sense.
Let me know if there's anything I can do.

**Comment by phated** [comment]
I'd like to see the tests you have, since i don't have any yet

**Comment by doowb** [comment]
[PR sent to `vinyl-prepare`](https://github.com/gulpjs/vinyl-prepare/pull/1). We can discuss there and I can make changes and additions as needed.

**Comment by krnlde** [comment]
As mentioned in gulpjs/vinyl-prepare/pull/1 I would like to ask for the current state of this issue. The progress seem to have stopped since September 2016. What can we do?

**Comment by phated** [comment]
@krnlde why haven't you looked at the open issue on that repository? https://github.com/gulpjs/vinyl-prepare/issues

**Comment by krnlde** [comment]
Everything is scattered. I don't understand what is left to close this issue and others. Gulp 4 is in the pipeline for about a year now. From outside it looks like there is no progress at all since about half a year (https://github.com/gulpjs/gulp/milestone/1). I don't understand the  structure of the issues. Again, what can we do to make some progress?

**Comment by phated** [comment]
@krnlde That's extremely disrespectful, as I spend a lot of time organizing, labeling and linking issues.  I also have created an organization level Github "Project" (that this issue is even linked to...) at https://github.com/orgs/gulpjs/projects/1.  Everything that needs help is labeled as "help wanted" so using Github search can find you everything that's out there (see https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+org%3Agulpjs+label%3A%22help+wanted%22).  On top of all that, the main gulp repo has a few "milestone" issues that have lists of things to tackle.  These types of comments would be much more suited for those issues.

Please use the tools that are available instead of jumping on a random thread and asking what to do.

I'm going to lock this issue and clean up your comments because they don't belong here and this thread doesn't seem to need any more discussion (as vinyl-prepare is being worked on and just needs to be integrated once finished).

**Comment by phated** [comment]
Basic support for this has landed in master but I still need to some more work on this and get the libraries to 1.0 before the vinyl-fs@3 release.

**Comment by phated** [comment]
These changes are being backed out and will be revisited in a future release.  I'll open a new issue after the 3.0 release.
