### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by phated** [gulpjs/vinyl-fs#255]
The performance of vinyl-fs seems to have tanked.  Need to profile this.

**Comment by erikkemperman** [comment]
Haven't profiled, but I wonder if at least some of the degradation might be due to `resolve-options`, which is binding function-options and -fallbacks per invocation of the `resolve` function, instead of just once, one scope up, once per `resolver`.

So if X vinyls pass through a pipeline with Y stages, constructed off a single options object, the same function is uselessly bound to the same context, X * Y times over.

Unfortunately I haven't had time to make a proper PR this evening, and I really have to sign off shortly (it's late here and I've had a pint :-)) but would be interested to find out something like the following makes any difference:

https://github.com/erikkemperman/resolve-options/commits/refactor

BTW What kind of scenarios are you benchmarking, and which versions are you contrasting?

**Comment by phated** [comment]
@erikkemperman I don't doubt that `resolve-options` has caused degradation (it was actually the first thing i thought about, haha). However, we've even tanked when 1-2 files are being passed through so I'm not sure __how much__ is caused by that new module.

**Comment by phated** [comment]
I was comparing really old vinyl-fs (that shipped with gulp 3.x), 2.4.4, master and your `use-cache` branch.

**Comment by phated** [comment]
A quick tests on a couple of runs seems to indicated that your `resolve-options` refactor is reducing throughput (using 1000 files).

**Comment by phated** [comment]
Or maybe my computer is being annoying and the performance stayed about the same...

**Comment by phated** [comment]
It seems the biggest performance issue is that `is-utf8` scans every byte of a buffer to know if it is UTF8-encoded.  I'm wondering if we can just sniff the first ~7 bytes like the streaming interface does. @jonschlinkert @doowb any thoughts?

**Comment by erikkemperman** [comment]
@phated I was just looking into this a bit. Definitely we don't want (or need) to sniff every single byte to check that the buffer is valid UTF8, of course. But have you actually measured this to make a big impact?

I'm asking because I noticed that Sindre Sorhus' module, at the version which was used here before, does pretty much the same thing:
https://github.com/sindresorhus/strip-bom/blob/851b9c126dba9561cc14ef3dc2634dcc11df4d11/index.js#L11

Incidentally, I am curious what made you swap out these dependencies -- instead of just updating them. Not that I doubt the quality of the replacements, mind you. But just saying: if the reason was that strip-bom also checked strings, which is never applicable for vinyl contents, then note that that's no longer the case and Sindre has split off `strip-bom-buf`.

**Comment by phated** [comment]
@erikkemperman many reasons, but namely that they dropped support for node 0.10 for absolutely no gain.  Message me privately if you need more information.

However, with your changes to `remove-bom-buffer`, I think that our performance will be much better (even when I don't turn off that functionality).

Other than removing the BOM, I think our "performance" problems are actually caused by the suite I was looking at because my tests are showing completely different results.  I'm going to close this.
