### ISSUE TITLE
src breaks when absolute path contains [ or ] characters

### ISSUE THREAD

**Issue by phated** [gulpjs/vinyl-fs#307]
As discovered in https://github.com/gulpjs/gulp/issues/2296 - `src()` won't pick up files when the absolute path contains characters like `[` or `]` (or maybe when those 2 are combined?).

@erikkemperman have we encountered this before?

**Comment by erikkemperman** [comment]
Square brackets should not confuse node-glob, one would hope... Although I’ve run into platform-specific quirks before. I would check what’s being exchanged with node-glob, first of all.

**Comment by phated** [comment]
Yeah, unfortunately the issue was happening on Windows x64, which I don't have (I could try replicating on AppVeyor which is Windows x32, I think).

**Comment by erikkemperman** [comment]
Actually Travis has Windows support too. It's labelled as early access but works fine from what I have seen thus far. Can't easily find whether it is 32 or 64 bits, but I would expect the latter. If I find some time I might attempt to rework the Travis setup to run on Linux, Mac and Windows. If I get that to work I'll have probably also discovered if it's 32 or 64 bits.

Does that sound all right, or are you attached to having separate CI providers?

**Comment by erikkemperman** [comment]
I went ahead and quickly tried this:
https://github.com/erikkemperman/vinyl-fs/commits/travis-multi-os
The Linux and MacOS builds pass, for all Node versions. The Windows builds fail on two unit-tests:
https://travis-ci.org/erikkemperman/vinyl-fs/builds/508369781

I googled a bit and this might be due to "developer mode" being set on Appveyor VMs but not Travis? But I'm not really sure, and I don't have a Windows box to debug this properly... If anyone knows more about this, please do chime in.

Anyway, I think it might be good to have just one CI provider. And at least I've now confirmed that Travis' Windows builds are x64.

**Comment by phated** [comment]
That's interesting that they have Windows support now.  We've been recommended to move to Azure Pipelines which has support for all 3 platforms as well.

**Comment by erikkemperman** [comment]
Is Azure free for open source projects as well? I don’t have anything against them, as I have never used the platform. But I’m pretty content with Travis thus far.

Anyway, it appears that in the short term we might try to use a Windows worker on Travis to debug the issue at hand.

**Comment by phated** [comment]
I agree, I'm still working on getting it added to the main gulp repo and then will need to propagate it out to the others.

> Is Azure free for open source projects as well?

They are free for open source and give 10 concurrent builds (and offered to bump that number up for us).

**Comment by marwanhilmi** [comment]
Ran into this issue recently on macOS as well.

```
"gulp-debug": "^4.0.0",
"vinyl-fs": "^3.0.3"
...
```

**Comment by phated** [comment]
This will be fixed in vinyl-fs v4 via glob-stream v8. See https://github.com/gulpjs/glob-stream/pull/117 for more information.
