### ISSUE TITLE
Allow overriding `highWaterMark`

### ISSUE THREAD

**Issue by ehmicky** [gulpjs/vinyl-fs#308]
From what I've understood (correct me if I'm wrong) streams in object mode have a default `highWaterMark` of `16` which means only 16 vinyl files are processed at a time in parallel.

While `16` is probably a safe default to prevent exhausting the machine resources, it might be good to allow users to override that value for increased performance?

**Comment by phated** [comment]
We took this away in a major bump, as we found that it was masking a bigger problem with streams not being drained properly. 

It doesn't make sense to bump the HWM on object streams, the way it does on a buffer stream.

**Comment by ehmicky** [comment]
The first part makes sense.

For the second part: correct me if I'm wrong but the `highWaterMark` on object streams is basically the maximum number of objects processed at once?

Some Gulp plugins might be quite slow. E.g. some create a child process like `gulp-shell`. In that case increasing the `highWaterMark` would improve the performance quite a lot in some environments.

**Comment by phated** [comment]
You are close. HWM is the size of the buffer where objects are stored before they are read or written.  The next stream in the pipeline reads from the buffer and frees up the queue, that stream will continue reading until its "write" buffer is filled. So a plugin like gulp-shell would just keep reading objects and trying to process them as fast as possible, since it would be slow to "write" the results, it likely would never fill that buffer.

I hope that makes sense, streams are so confusing.

**Comment by ehmicky** [comment]
If I understand you correctly you mean when doing:

```js
const ostream = gulp.src(...)
const istream = gulpShell(...)
ostream.pipe(istream)
```

  - `ostream` keeps adding files until it fills up a buffer of `16` files.
  - `istream` keeps reading files from `ostream`'s buffer, emptying it at the same time.
  - `istream` add each processed file (i.e. after each slow shell command has finished) to its own buffer. That buffer is used by the next command in the pipeline.

If I got this right then the streams will rarely hit the HVM. Instead lots of shell commands will be queued in parallel.

Let me know if I got this right. My issue is that I actually tried it myself with a `sleep 10` command and it seemed that only 16 shell commands were processed at any given time.

**Comment by phated** [comment]
From my understanding, that is how a stream is supposed to operate - I even reviewed the nodejs docs before answering and they seemed to confirm it.  In my experience, streams (especially object streams) rarely hit the HWM.

The issue you are seeing with gulp-shell is actually the "masking of the bigger problem" that I mentioned previously.  Your stream is never being drained because the author implemented it as a Transform stream instead of a Writeable like it should have been.  If you don't have a Writeable stream at the end of your pipeline, it'll never be drained and your HWM will get filled up at those 16 objects.

Streams returned from gulp tasks are drained automatically if they aren't a Writeable stream, since this issue was pretty common within the ecosystem.

Hopefully that helps.

**Comment by ehmicky** [comment]
`gulp-shell` is based on `through2` (like most Gulp plugins) which is a `Transform` stream indeed.

Sorry to deviate from the original problem but I would like to get this right because I am currently developing my own Gulp plugin [`gulp-execa`](https://github.com/ehmicky/gulp-execa/blob/master/src/stream.js).

Why aren't Transform streams the correct type here? Gulp plugins usually take some input (Vinyl file), modify it then return it as is. Since they are returned as is, does this mean they conceptually map to Writeable streams instead of Transform? No worries if you don't have time to delve into this, I think I might just need to update my knowledge of Node.js core streams.

**Comment by phated** [comment]
If you look at the gulp-shell docs, they are using `gulp.src` as just a globbing library (and they say not to do it anymore).  They also don't pipe the stream anywhere, so they are saying to use it as the "end of the pipeline", thus it should be a Writeable stream.  You **cannot** end a stream on a transform stream, they just don't work like that.

One other thing about your module - please don't use promises (async/await) inside streams, it just makes a mess of everything.

**Comment by ehmicky** [comment]
About promises inside streams: what's the problem with it?

This plugin is mostly a wrapper around `execa`. I understand firing a bunch of child processes inside a stream is a bad idea. Most of time users should perform globbing outside of a stream, or let the command handle several files as arguments as once (through globbing, directory recursion, etc.).

So this plugin mostly adds Gulp-specific things around `execa` such as throwing a `plugin-error`, using `fancy-log` and a nice syntax for Gulp tasks that are only a shell command.

But there might still some use cases where a shell command needs to be fired repeatedly over a bunch of files and there's no way around it. Using Bash specifics like `for` loops is not an option on Windows `cmd.exe`. Because of that I implemented a method to fire a shell command in a stream.

How can someone fire shell commands in a stream without using promises?

**Comment by phated** [comment]
@ehmicky this is exceeding the scope of what I'd like to handle here.  Maybe if I can start [my office hours concept](https://twitter.com/gulpjs/status/1102305262742827008), then we can explore some of those questions more.

**Comment by ehmicky** [comment]
No worries I understand.

Just to make the above point clearer, some shell commands only take single file paths as input. Those shell commands need to be repeated in order to be applied on several files.

One way to do it in a cross-platform way would be to use `Promise.all()` + `execa()`. I thought using a stream instead of `Promise.all()` would work just fine as I was not aware of any issues with mixing promises and streams.

No need to answer this message if you don't have the time, I just wanted to make my former message clearer.
