### ISSUE TITLE
`file.contents = stream` does not work

### ISSUE THREAD

**Issue by ehmicky** [gulpjs/vinyl-fs#310]
`gulpfile.js`:

```js
const { spawn } = require('child_process')

const { src, dest } = require('gulp')
const through2 = require('through2')

module.exports.default = () =>
  // src('empty.js', { buffer: false }) does not solve this bug
  src('empty.js')
    .pipe(
      through2.obj((file, encoding, callback) => {
        file.contents = spawn('echo', ['hello']).stdout
        callback(null, file)
      }),
    )
    .pipe(dest('dest'))
```

`./empty.js` is empty. 
`./dest/` is an existing but empty directory.

`package.json`:

```json
{
  "name": "gulp-bug",
  "version": "0.0.1",
  "devDependencies": {
    "gulp": "^4.0.2",
    "through2": "^3.0.1"
  }
}
```

In the terminal:

```bash
$ gulp
[15:40:17] Using gulpfile ~/Desktop/gulp-bug/gulpfile.js
[15:40:17] Starting 'default'...
[15:40:17] Finished 'default' after 17 ms
$ cat dest/empty.js
# File is empty
```

I am expecting `./dest/empty.js` to contain the string `hello`, but instead it is empty.

Node `12.2.0`, Ubuntu `19.04`.

**Comment by phated** [comment]
I've debugged this and this isn't an issue with vinyl or vinyl-fs. Instead, it is an issue with the `stdout` SocketStream in node because it starts streaming immediately and can't even be paused.

When working with streams that don't behave correctly, you can wrap it in something like `lazystream` (though I would recommend finding a better maintained project).

I'll be adding an integration test that uses a stream that behaves to close this out.
