### ISSUE TITLE
Do you mind to fix vinyl-fs 0.3.14 on nodejs 12 so that gulp v3 can still work?

### ISSUE THREAD

**Issue by 3cp** [gulpjs/vinyl-fs#311]
I am referring gulpjs/gulp#2324 that gulp v3 breaks because vinyl-fs 0.3 depends on graceful-fs v3 which doesn't work on Nodejs v12.

I understand gulp v3 is not supported anymore. But the fix is too simple.

I tested vinyl-fs 0.3.14 with one char change here:

https://github.com/gulpjs/vinyl-fs/blob/e53bcdd52a034166fdc8b1c1516cbc15051d3bb5/package.json#L17

Upgrade graceful-fs from `"graceful-fs": "^3.0.0"` to `"graceful-fs": "^4.0.0"`, all tests still pass.

As graceful-fs itself said, v4 is a drop-in replacement of v3. So my question is can we have a patch release of vinyl-fs 0.3.15 that can give all gulp v3 users a relief?

**Comment by phated** [comment]
Unfortunately that cannot happen:
1. The graceful-fs team bumped the major because they didn't know the ramifications the updates would have on consumers. That is a breaking change.
2. I determined that the runtime environment would be effected and so that should be considered a breaking change. You can't fit that into the semver range you desire without potentially breaking users.
3. As you said, those versions are no longer supported (and haven't been for a very very very long time).

As a solution, if you are sure graceful-fs won't break your personal environment, you probably want to use something like "resolutions" to replace 3 with 4. Though I highly suggest upgrading to gulp4 because it has been published for almost 2 years now.

**Comment by 3cp** [comment]
I am little disappointed, but I do applaud your strict stand on semver semantics. We were all annoyed by libs that ship breaking change without bumping major version.
