### ISSUE TITLE
Create a way for changing the vinyl files before filtering "since"

### ISSUE THREAD

**Issue by FCO** [gulpjs/vinyl-fs#316]
That should be a way of passing a function for `src` that would receive each vinyl file before any filter, and it could change that file.

My use-case is I have an src using `since`. But those files have dependency files, and I'd like to not filter the file if its dependencies have changed after the `lastRun`.

So, my solution for that would be, for each file, before any filtering, it would find all its dependencies, get the highest mtime, and set the vinyl file's mtime for that. That way all the files with changes on its dependencies would be reprocessed.

**Comment by contra** [comment]
@FCO Have you tried not using the built-in `since` and making your own filter stream that has your custom logic? I think it would be useful to see it done both ways to make a judgement call if a new API is warranted in `src`. Not opposed to adding a custom `filter` prop (and running `since` after it) but I think ultimately piping to another stream to do that is more flexible.

**Comment by phated** [comment]
Building what you are describing **on top** of `gulp.src` is an extremely inefficient idea. It sounds like you want to build your own [Vinyl adapter](https://github.com/gulpjs/vinyl-fs#what-is-a-vinyl-adapter).

If you continue continue down your inadvisable path, all options in vinyl-fs can take a value or function, as noted at https://github.com/gulpjs/vinyl-fs#options
> All options can be passed a function instead of a value. The function will be called with the vinyl File object as its only argument and must return a value of the expected type for that option.

Note that those functions are synchronous, so you'd be blocking your entire process while trying to determine a dependency graph, which is why I wouldn't do it.
