### ISSUE TITLE
Switch to fast-glob?

### ISSUE THREAD

**Issue by phated** [gulpjs/vinyl-fs#317]
It looks like fast-glob implements something very similar to our glob-stream library. Should we switch to use it instead of maintaining that ourselves? Honestly, I'd like the glob stuff to live inside the gulpjs org because we've had so much problems with `node-glob` in the past.

Ref https://github.com/gulpjs/glob-parent/pull/26#issuecomment-602181444

cc @mrmlnc @coreyfarrell @erikkemperman

**Comment by terinjokes** [comment]
> Honestly, I'd like the glob stuff to live inside the gulpjs org 

I second this for the same reason; we keep being burned by external projects with no API stability guarantees.

**Comment by phated** [comment]
Their docs also state:
> ⚠️ This package does not respect the order of patterns. First, all the negative patterns are applied, and only then the positive patterns. If you want to get a certain order of records, use sorting or split calls.

Which is functionality that gulp users rely on heavily, so that might be a problem.

**Comment by coreyfarrell** [comment]
This idea is concerning due to globbing being a minefield of edge cases.  I'm not saying it's a bad idea just that any action here is scary and almost guaranteed to produce bug reports from users.  https://github.com/nodejs/tooling/issues/38 is probably worth a look since it had some discussion comparing glob/minimatch vs fast-glob/micromatch.

One thing that would make me more comfortable would be a data set that can be iterated for compliance testing to be run against both modules (maybe minimatch vs micromatch instead of glob vs fast-glob).  This is a big ask so I'm not expecting anyone to make this effort, just thinking out loud that movement between glob implementations would be easier if we could generate a report showing things that are expected to start or stop working.  I don't think this effort would be worth while without buy-in from authors of both minimatch and micromatch, we'd want the data set to be structured so those modules could actually use it to generate large parts of their own test coverage.
