### ISSUE TITLE
Use new buffer methods

### ISSUE THREAD

**Issue by phated** [gulpjs/vinyl-fs#318]
Ref #304

**Comment by coreyfarrell** [comment]
vinyl-fs only uses `new Buffer()` from tests.  For end-users this issue needs to be fixed in `vinyl-sourcemap` which performs `new Buffer()` directly and through the `append-buffer` dependency.

I'll post a PR for removing `new Buffer()` from the tests here once CI is working.  Ping to https://github.com/gulpjs/.boilerplate/issues/3 :smile:, I'd switch this to Github Actions but I'm not sure if partially updating would mess with the eventual full update.

**Comment by jimmywarting** [comment]
I could help out with converting all the `new Buffer()` constructor when the GH action are in place. 
Haven't contributed to gulp before but this seems like a easy entrances to start helping out if you want a extra hand.

Add a "Blocked on GH action" and then assign this issue to me if you want

**Comment by contra** [comment]
@jimmywarting Absolutely this would be a great first contribution!
