### ISSUE TITLE
empty array passed to src should return empty stream

### ISSUE THREAD

**Issue by yocontra** [gulpjs/vinyl-fs#40]
RE https://github.com/gulpjs/gulp/issues/712

**Comment by vbud** [comment]
I've been using the gulp 4.0 alpha, and it looks like this decision was reverted in one of the recent major bumps of vinyl-fs. Specifically, whichever bump made [is-valid-glob](https://github.com/jonschlinkert/is-valid-glob) a dependency, as the behavior was reverted in that repo (https://github.com/jonschlinkert/is-valid-glob/commit/e3ce0775bf3b05a2e6c67905c52ff20520ca9c8e).

I agree with the logic @wesleytodd laid out in gulpjs/gulp#712. Is there a reason why you reversed your stance @contra?

**Comment by contra** [comment]
@vbud no it was an unintentional side effect (regression) of switching to is-valid-glob - open a ticket on their repo and they can fix it there and it will be automatically pulled into the vinyl-fs repo

**Comment by vbud** [comment]
Done - thanks for the quick response.

**Comment by doowb** [comment]
FYI... empty arrays will cause `glob-stream` to throw a `Missing positive glob` error. A check for empty arrays will need to be added back to vinyl-fs or glob-stream and return a passthrough stream.

**Comment by jonschlinkert** [comment]
> no it was an unintentional side effect (regression) of switching to is-valid-glob

Isn't this from https://github.com/jonschlinkert/is-valid-glob/commit/e3ce0775bf3b05a2e6c67905c52ff20520ca9c8e?

**Comment by contra** [comment]
Actually yeah, I remember this now. Using empty arrays in src led to really fucking insane anti-patterns in gulpfiles so we explicitly disabled it to discourage people from doing crazy shit like `gulp.src([]).pipe(exec('some command'))` when they should just use normal js code to do it

**Comment by vbud** [comment]
Interesting.

Just so the problem is clear, this will make [usage of packages like main-bower-files with gulp a bit trickier](https://github.com/ck86/main-bower-files#usage-with-gulp). Any time we want to hand an array of files resolved by something else, e.g. globby or main-bower-files, we will have to check if the array is empty. Which results in code like this, since we'll have to terminate the task early:

```js
function moveVendorCssFiles(cb) {
	var bowerCss = mainBowerFiles({filter: '**/*.css'});
	if(bowerCss.length === 0) {
		cb();
		return;
	}
	return gulp.src(bowerCss, {base: paths.bowerComponents})
	...
```

Which is fine with me, though it would be nice if the error message was clearer. Today the message is just: `Error: Invalid glob argument:`. Something like `Error: Invalid glob argument: empty arrays are not allowed` would be better.

 I'm also open to better solutions to deal with the new behavior.

**Comment by wesleytodd** [comment]
`alternateUseCase !== antiPattern`

@vbud makes a great arguments for this being an alternate use case.  Originally we had a very similar reason for running into this.  We are no longer relying on this working, and also have not updated.  Sounds like we wont be if this is going to stay like this.

**Comment by vbud** [comment]
I've encountered other issues today as well, so I'm thinking of retracting my above statement that this is "fine with me" :smile:.

It looks like glob-stream is also enforcing that individual file references in [glob arrays](https://github.com/gulpjs/glob-stream/blob/master/test/main.js#L496) or in [singular globs](https://github.com/gulpjs/glob-stream/blob/master/test/main.js#L487) must exist, otherwise a `'File not found with singular glob'` error is thrown.

With stricter policies like this going in place across the gulp ecosystem, any time I want to hand files to `gulp.src` that may not exist, I have to do two new things that I didn't have to do before:

1. "pre-resolve" files with [globby](https://github.com/sindresorhus/globby) before handing to `gulp.src`
2. *only* hand the files to gulp when there is at least one result, otherwise fire the callback so the task ends

This is definitely a painful change just to prevent people from doing things like `gulp.src([]).pipe(exec('some command'))`. @contra are there other dangerous anti-patterns that this is preventing? Because IMHO while I agree that the example you gave is an anti-pattern, there are multiple legitimate use cases that are now no longer possible.

And if you guys (gulp core team) do want to stick with this stricter behavior, would you at least consider adding an `allowEmpty` flag we could pass into `gulp.src` that would enable the use cases @wesleytodd and I have described?

**Comment by phated** [comment]
@vbud that is very strange, as you are reporting the exact opposite of https://github.com/gulpjs/gulp/issues/1253 - Can you please open a new issue about this stuff or help debug the issue I just linked so we can resolve all of this stuff as part of a non-closed issue.  Thanks!

**Comment by contra** [comment]
Can anyone provide some more use cases from their gulp files where src is not handling glob resolution?

**Comment by vbud** [comment]
@phated [Done](https://github.com/gulpjs/gulp/issues/1253#issuecomment-144576527).

I'm happy to create a separate issue for this. Should I create it in gulp or in vinyl-fs?

**Comment by phated** [comment]
@vbud appreciate it.  I think the use case is related to gulp enough to put it there (also gets more eyes on it).  Please link that issue back in this thread.

**Comment by contra** [comment]
https://github.com/jonschlinkert/is-valid-glob/issues/3
